#!/usr/bin/env python3
"""Generates assets + ui/tokens.slint + ui/walls.slint from the FINAL html design (ground truth)."""
import re, json, base64, io, sys
import numpy as np
from PIL import Image, ImageFilter, ImageEnhance
HTML=sys.argv[1]; TOK=sys.argv[2]
PALS=["blue","orange","bone","pistachio","violet","rose","teal","gold","graphite","wine"]
STYLES=["bokeh","aurora","silk","horizon","plain"]
tok=json.load(open(TOK))
def col(s):
    s=s.strip()
    m=re.match(r'rgba?\(([^)]*)\)',s)
    if m:
        p=[float(x) for x in re.split(r'[ ,/]+',m.group(1).strip()) if x]
        r,g,b=[int(round(x)) for x in p[:3]]; a=p[3] if len(p)>3 else 1.0
        return (r,g,b,int(round(a*255)))
    m=re.match(r'color\(srgb ([^)]*)\)',s)
    if m:
        p=[float(x) for x in m.group(1).split()]
        return tuple(int(round(x*255)) for x in p[:3])+(255 if len(p)<4 else int(round(p[3]*255)),)
    raise ValueError(s)
hexc=lambda c:'#%02x%02x%02x%02x'%c
VARS=["a1","a2","b1","b2","deep","acc1","acc2","acct","g1","g2","hi","lo","sh","tx","mu","smu","track","lp","ttl","like","sheet"]
out=["// GENERATED by scripts/gen_assets.py from Velora-FINAL.html - do not edit by hand.",
     "// Index = palette_index*2 + (dark ? 1 : 0); palette order: "+", ".join(PALS),"export global Pal {"]
for v in VARS:
    arr=[]
    for p in PALS:
        for m in ("light","dark"): arr.append(hexc(col(tok[f"{p}_{m}"][v])))
    out.append(f"    out property <[color]> {v}: [{', '.join(arr)}];")
out.append("}")
open('ui/tokens.slint','w').write('\n'.join(out)+'\n')
s=open(HTML).read()
m=re.search(r'<script>const IMG=(\{.*?\});</script>',s,flags=re.S); IMG=json.loads(m.group(1))
full=[];blur=[]
for st in STYLES:
    for p in PALS:
        for md in ("light","dark"):
            uri=IMG[st][f"{p}_{md}"]; raw=base64.b64decode(uri.split(',',1)[1])
            im=Image.open(io.BytesIO(raw)).convert('RGB').resize((360,780),Image.LANCZOS)
            im.save(f'assets/wall/{st}_{p}_{md}.jpg',quality=72,optimize=True)
            b=im.resize((45,98),Image.BILINEAR).filter(ImageFilter.GaussianBlur(1.3))
            b=ImageEnhance.Color(b).enhance(1.8); b=ImageEnhance.Brightness(b).enhance(1.07)
            b.save(f'assets/blur/{st}_{p}_{md}.jpg',quality=85)
            full.append(f'@image-url("../assets/wall/{st}_{p}_{md}.jpg")'); blur.append(f'@image-url("../assets/blur/{st}_{p}_{md}.jpg")')
N=384; yy,xx=np.mgrid[0:N,0:N]; cx=cy=(N-1)/2; R=N/2-1.5; d=np.hypot(xx-cx,yy-cy)/R
def sm(a,b,x):
    t=np.clip((x-a)/(b-a),0,1); return t*t*(3-2*t)
disc=[]
for p in PALS:
    for md in ("light","dark"):
        t=tok[f"{p}_{md}"]; a1=np.array(col(t['acc1'])[:3],float); a2=np.array(col(t['acc2'])[:3],float); b1=np.array(col(t['b1'])[:3],float)
        dark=md=="dark"; ink=np.array([255,255,255.]) if dark else np.array([15,23,42.])
        img=np.zeros((N,N,4)); edge=sm(1.0,0.985,d)
        body=(0.10 if dark else 0.07)+0.06*(1-np.clip(d,0,1))**1.5
        ring=0.5+0.5*np.cos(2*np.pi*(d*R)/7.5); groove=(0.10 if dark else 0.09)*(ring**6)
        img[...,:3]=ink; img[...,3]=np.clip(body+groove,0,1)*edge*255
        rim=np.exp(-((d-0.985)/0.012)**2)*(0.55 if dark else 0.30); img[...,3]=np.clip(img[...,3]+rim*255*edge,0,255)
        L=d/0.38; g=np.clip(((xx-cx)+(yy-cy))/(2*R*0.38)*0.5+0.5,0,1)[...,None]
        lc=a1*(1-g)+a2*g
        hl=np.exp(-(np.hypot(xx-(cx-0.24*R),yy-(cy-0.33*R))/(0.35*R))**2*2.2)[...,None]
        lc=lc+(255-lc)*hl*0.55
        la=sm(1.0,0.97,L)
        for k in range(3): img[...,k]=img[...,k]*(1-la)+lc[...,k]*la
        img[...,3]=img[...,3]*(1-la)+255*la
        lr=np.exp(-((L-0.985)/0.03)**2)*0.6
        for k in range(3): img[...,k]=img[...,k]*(1-lr)+255*lr
        hole=sm(0.085,0.075,L)
        for k in range(3): img[...,k]=img[...,k]*(1-hole)+b1[k]*hole
        img[...,3]=np.clip(img[...,3]+hole*255,0,255)
        Image.fromarray(np.clip(img,0,255).astype(np.uint8),'RGBA').resize((256,256),Image.LANCZOS).save(f'assets/disc/{p}_{md}.png',optimize=True)
        disc.append(f'@image-url("../assets/disc/{p}_{md}.png")')
ang=(np.degrees(np.arctan2(xx-cx,-(yy-cy)))+360-30)%360/360
def seg(a,b,c,x): return np.where(x<b,sm(a,b,x),1-sm(b,c,x))*((x>=a)&(x<=c))
sheen=(0.30*seg(0.0,0.09,0.20,ang)+0.22*seg(0.52,0.61,0.72,ang))*(d<=1.0)*sm(1.0,0.985,d)
S=np.zeros((N,N,4),np.uint8); S[...,:3]=255; S[...,3]=np.clip(sheen*255,0,255).astype(np.uint8)
Image.fromarray(S,'RGBA').resize((256,256),Image.LANCZOS).save('assets/disc/sheen.png',optimize=True)
w=["// GENERATED by scripts/gen_assets.py - do not edit by hand.",
   "// Index = style*20 + palette*2 + dark ; style order: "+", ".join(STYLES),
   "export global Walls {","    out property <[image]> full: ["+",\n        ".join(full)+"];",
   "    out property <[image]> blur: ["+",\n        ".join(blur)+"];",
   "    out property <[image]> disc: ["+",\n        ".join(disc)+"];",
   '    out property <image> sheen: @image-url("../assets/disc/sheen.png");',"}"]
open('ui/walls.slint','w').write('\n'.join(w)+'\n')
print('ok',len(full),len(blur),len(disc))
