#!/usr/bin/env python3
import re, sys
html=open(sys.argv[1]).read()
syms=re.findall(r'<symbol id="i-([a-z0-9]+)" viewBox="0 0 (\d+) (\d+)">(.*?)</symbol>',html,flags=re.S)
def num(x): return float(x)
def circle(cx,cy,r): return f"M{cx-r:g} {cy:g}a{r:g} {r:g} 0 1 0 {2*r:g} 0a{r:g} {r:g} 0 1 0 {-2*r:g} 0z"
def rect(x,y,w,h,rx): 
    rx=min(rx,w/2,h/2)
    return f"M{x+rx:g} {y:g}H{x+w-rx:g}A{rx:g} {rx:g} 0 0 1 {x+w:g} {y+rx:g}V{y+h-rx:g}A{rx:g} {rx:g} 0 0 1 {x+w-rx:g} {y+h:g}H{x+rx:g}A{rx:g} {rx:g} 0 0 1 {x:g} {y+h-rx:g}V{y+rx:g}A{rx:g} {rx:g} 0 0 1 {x+rx:g} {y:g}z"
out=["// GENERATED by scripts/gen_icons.py from the <symbol> icons of Velora-FINAL.html","export global Ic {"]
for name,w,h,body in syms:
    d=[]
    for m in re.finditer(r'<(path|circle|rect|line)\b([^>]*)/?>',body):
        tag,attrs=m.group(1),dict(re.findall(r'([a-zA-Z-]+)="([^"]*)"',m.group(2)))
        if tag=='path': d.append(attrs['d'].strip())
        elif tag=='circle': d.append(circle(num(attrs['cx']),num(attrs['cy']),num(attrs['r'])))
        elif tag=='rect': d.append(rect(num(attrs['x']),num(attrs['y']),num(attrs['width']),num(attrs['height']),num(attrs.get('rx','0'))))
        elif tag=='line': d.append(f"M{attrs['x1']} {attrs['y1']}L{attrs['x2']} {attrs['y2']}")
    if name=='logo': continue
    out.append(f'    out property <string> {name}: "{" ".join(d)}";')
out.append("}")
open('ui/icons_data.slint','w').write("\n".join(out)+"\n"); print(len(syms),'icons')
